### ISSUE TITLE
[issue][frontend] Importing fonts giving console errors

### ISSUE THREAD

**Issue by anonymous-sidhax** [Collaborative-Open-Source-Projects/learnxperience#33]
Getting 404 for fonts 
![image](https://github.com/user-attachments/assets/2fcbc327-08ad-47e5-98a3-97872f3a29e1)
Probably need to correct the path
![image](https://github.com/user-attachments/assets/b937993a-eaef-43f7-82e9-652c86e33ab9)

**Comment by ridwanyinus** [comment]
Issue #33 has been resolved.  I updated the 'font'  path from /app/fonts to /public/fonts

The fix can be reviewed in PR #39.  Please review the changes and let me know if additional modifications are required.

Closing the issue now. Thanks!
